### ISSUE TITLE
Add flake8 to pre-commit

### ISSUE THREAD

**Issue by rathorevaibhav** [avantifellows/plio-backend#118]
**Describe the task**
Flake8 was added and then removed from [this PR](https://github.com/avantifellows/plio-backend/pull/95) due to failing CI. It needs to be added and CI fixes to be done separately.

**Expected behavior**

Add flake8 to pre-commit. Add the following line of codes to pre-commit.yml file. The pre-commit CI should pass based on above configs
```yaml
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.0'
    hooks:
    -   id: flake8
        args:
        # these are errors that will be ignored by flake8
        # check out their meaning here
        # https://flake8.pycqa.org/en/latest/user/error-codes.html
        - "--ignore=E501"
```
